from graph.state import GraphState
from graph.tools.github_tools import create_pull_request_review


def update_pull_request(state: GraphState):
    print("....... UPDATING PULL REQUEST .......")

    findings = state["findings"]

    if not findings:
        body = """
## CodeGuard Review

CodeGuard reviewed this pull request and found no actionable issues.
"""
    else:
        sections = []

        for finding in findings:
            sections.append(
                f"""
### {finding.category.upper()} — Severity {finding.severity}

**Description:**
{finding.description}

**Suggestion:**
{finding.suggestion}
"""
            )

        body = f"""
## CodeGuard Review

CodeGuard found **{len(findings)} actionable issue(s)** in this pull request.

{"".join(sections)}

---
*This review was generated by CodeGuard and approved by a the project manager*.*
"""

    result = create_pull_request_review(body)

    print(f"GitHub review created: {result['html_url']}")

    return {
        "github_review_url": result["html_url"]
    }